# golangci-lint configuration for osoba project
version: "2"

run:
  timeout: 5m
  go: "1.24"
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - goconst
    - gocognit
    - asciicheck
    - gofumpt
    - prealloc
    - predeclared
    - nilerr
    - exhaustive
    - exportloopref
    - whitespace
    - wsl
    - godot

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/douhashi/osoba
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  godot:
    scope: declarations
    capital: true
  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    - path: cmd/
      linters:
        - gocognit
    - text: "exported (method|function|type|const) .* should have comment or be unexported"
      linters:
        - revive
        - golint

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true