# .golangci.yml
run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/douhashi/osoba