# golangci-lint configuration for osoba project
version: "2"

run:
  timeout: 5m
  go: "1.24.5"
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/douhashi/osoba
  misspell:
    locale: US
  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true