# golangci-lint configuration for osoba project
version: "2"

run:
  timeout: 5m
  go: '1.24.5'
  tests: true

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
  
formatters:
  default: none
  enable:
    - gofmt
    - goimports

linters.settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  staticcheck:
    checks: ["all"]

formatters.settings:
  goimports:
    local-prefixes: github.com/douhashi/osoba

linters.exclusions:
  paths:
    - vendor
    - .git
    - .github
  rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true
      sort-results: true