# 最小限の設定ファイルサンプル

log:
  level: debug

github:
  poll_interval: 10s
  auto_plan_issue: true
  auto_merge_lgtm: true   # 排他制御により安全に動作
  auto_revise_pr: true

tmux:
  session_prefix: "osoba-"

claude:
  phases:
    plan:
      args: ["--dangerously-skip-permissions"]
      prompt: "/osoba:plan {{issue-number}}"
    implement:
      args: ["--dangerously-skip-permissions"]
      prompt: "/osoba:implement {{issue-number}}"
    review:
      args: ["--dangerously-skip-permissions"]
      prompt: "/osoba:review {{issue-number}}"