github:
  # 実際のGitHubトークンを設定してください
  token: "your_github_token_here"
  owner: "douhashi"
  repo: "osoba"
  poll_interval: 10s
  max_retries: 3
  retry_base_delay: 1s
  labels:
    plan: "status:needs-plan"
    ready: "status:ready"
    review: "status:review-requested"